### ISSUE TITLE
Refactor AssetId

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/PINT#115]
## Issue summary

Currently, we have numeric AssetId in `pallet-asset-index`, should we refactor it into another type?

https://github.com/ChainSafe/PINT/blob/49ce26841414367682fca48f25874ac55c6822a6/pallets/asset-index/src/lib.rs#L94

## Other information and links

- [Acala/primitives/Currency](https://github.com/AcalaNetwork/Acala/blob/4dedc2feaddf416861c26af861edb31716f7ac62/primitives/src/currency.rs#L208-L212)
- [polkadot/xcm/xcm-executor](https://github.com/paritytech/polkadot/blob/c1940f13aeebf1e46be6f65fe14c0cbd65af8c77/xcm/xcm-executor/src/assets.rs#L21)
- https://github.com/AcalaNetwork/Acala/pull/1073

- #105
- #102

**Comment by mattsse** [comment]
There are several options, as discussed in #105 our asset identifiers are dynamic, meaning, something like,

```rust
enum AssetId {
  Saft(id),
  Liquid(id)
}
```

does not really work, because a saft asset id will eventually become a liquid asset.

I think we should stick with simple numeric types, but accept additional [`AssetMetadata`](https://github.com/paritytech/substrate/blob/master/frame/assets/src/types.rs#L92) when creating assets and store that in the registries.
