### ISSUE TITLE
Conflict MultiLocation required between xtokens and remote-asset-manager

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/PINT#210]
## Issue summary

* Required `X2` in `xtokens`

https://github.com/open-web3-stack/open-runtime-module-library/blob/3bf16d6efc8c35039a062748ff20fa6db6e8faa0/xtokens/src/lib.rs#L323

* Required `X1` in `XcmSender`

https://github.com/paritytech/polkadot/blob/8a6af4412ffc6d327775310c9b4ff527f3345958/runtime/common/src/xcm_sender.rs#L30

## Other information and links

-

**Comment by mattsse** [comment]
Can you extend on that?
the xtokens check just makes sure that there is a chain part and a recipient part (e.g. the account where we want to deposit funds in) and passes this to the `XcmExecutor` which executes the XCM accordingly. The `XcmExecutor` will then use `XcmSender` internally.

this `XcmSender` requires X1 because this actually sends the XCM (sends them to exact location of X1)

**Comment by clearloop** [comment]
Just saw the check in `xtokens` is for `receipient`
