### ISSUE TITLE
Implement `deposit` API call

### ISSUE THREAD

**Issue by dutterbutter** [ChainSafe/PINT#25]
Implement `deposit` API call detailed in the specification under AssetIndex Pallet.
## Implementation details

- Dispatches transfer Call to relay chain to move DOTs into the PINT Index account
- Fetches PINT NAV and DOT price from price feed
- Mints PINT proportional to DOT deposit
- Updates index to reflect deposit

|  Param 	| Type    	| Desc                          	|
|:------:	|---------	|-------------------------------	|
| amount 	| Balance 	| Amount of DOT being deposited 	|

**Comment by mattsse** [comment]
Currently, the deposit of funds is expected to happen via cross-chain messages. A user must first send a certain amount of an asset, that is supported by PINT, from another chain to the equivalent PINT address via XCM. This will also require that PINT will the same SS58 prefix as its relay chain. As soon as the XCM arrives on PINT, corresponding tokens can be minted on PINT  ([downward transfer](https://wiki.polkadot.network/docs/en/build-parachains-rococo#downward-transfers)).
The deposited funds could be directly converted into PINT tokens based on the current exchange rate. However, there are possible scenarios in which an exchange might not be successful, e.g. there is currently no price pair available because an oracle for the currency is possibly locked.

Also XCM will takes a bit of time so when the call arrives on PINT the price (PINT/Asset) may have already changed. 
Therefore, an approach that supports a variety of balances for assets for each account would make sense, so that a deposit via XCM always increases the corresponding account balance of the user first. Only in a second step can assets deposited on PINT be invested put in the index (in exchange for PINT tokens), or possibly even exchanged for other assets first.
the same would happen if funds were withdrawn from the index. Thus, liquidating PINT tokens would first increase the balance of the user's chosen assets before the user can transfer them via XCM.

This multi-asset approach would look similar to [MultiCurrency](https://github.com/open-web3-stack/open-runtime-module-library/blob/master/traits/src/currency.rs#L16) identified by an asset identifier.
