### ISSUE TITLE
Implement `bond` API call 

### ISSUE THREAD

**Issue by dutterbutter** [ChainSafe/PINT#75]
Implement `bond` API call detailed in the specification under RemoteAssetManager Pallet.

## Implementation Details

Dispatch XCM message to bond assets in callers account

|  Param 	| Type    	| Desc                                      	|
|:------:	|---------	|-------------------------------------------	|
| id 	| AssetId 	| Asset being bonded 	|
| units 	| Balance 	| Amount to bond	|

**Comment by mattsse** [comment]
To earn rewards, added assets will be staked on their respective chains.
Bonding, as is unbonding #76, is a chain specific operation and therefor may be specific for each `AssetId` in the index.
For example on polkadot with DOT using the `staking` pallet and the `nominate` and `bond` extrinsic.
Some assets may not support staking, so `bond` and `unbond` should be a noop.

In order to stake via XCM, the `RemoteAssetManager` requires knowledge how to execute these routines (transacting Xcm calls: nomate+bond for example). This may require a runtime upgrade for every new asset that gets approved by the committee. unless it is be possible to store the bond + unbond call(s) in storage, like `assetId -> Call::bond`
