### ISSUE TITLE
`AssetPriceFeed not found` in the call `deposit` of pallet `asset-index`

### ISSUE THREAD

**Issue by clearloop** [ChainSafe/PINT#93]
## Issue summary

This `deposit`  function runs well in tests, but not in benchmarks, besides, met this issue also while I was writing the Javascript API of PINT in #83.

Guess need to ensure that a valid round has already submitted first, separating from #91 

## Other information and links

- https://github.com/ChainSafe/PINT/blob/4fcfc4fda293c1a973dd97ac8e1dd7010e4d944d/pallets/asset-index/src/tests.rs#L91
- https://github.com/ChainSafe/PINT/blob/4fcfc4fda293c1a973dd97ac8e1dd7010e4d944d/pallets/price-feed/src/lib.rs#L175

---

Could not use `pallet_chainlink_feed` in the benchmark of `pallet_asset_index`, these two pallets are not tight coupling, #94

**Comment by mattsse** [comment]
A `deposit` of a specific (liquid) asset is essentially a conversion from this very asset to PINT token. 
In order to determine the PINT/asset rate, a price feed for this asset is required, hence the error.

Before depositing an asset its price pair must have at least a valid round. 

For testing purposes, a mock price feed is used: 

https://github.com/ChainSafe/PINT/blob/main/pallets/asset-index/src/mock.rs#L174-L199


We could also depend on our price pair crate wich exports a `Feedbuilder`  

https://github.com/ChainSafe/PINT/blob/main/pallets/price-feed/src/mock.rs#L132

**Comment by clearloop** [comment]
> For testing purposes, a mock price feed is used:
> 
> https://github.com/ChainSafe/PINT/blob/main/pallets/asset-index/src/mock.rs#L174-L199
> 
> We could also depend on our price pair crate wich exports a `Feedbuilder`
> 
> https://github.com/ChainSafe/PINT/blob/main/pallets/price-feed/src/mock.rs#L132

Yep, but we can use `ChainlinkFeed<T>` in mock tests but not in benchmarks, for example, in `asset-index`

```rust
trait Config: frame_system::Config {

}
```

We only can use `AssetIndex<T>` and `System<T>` but not `ChainlinkFeed<T>`, because we don't have this trait bound in the `Config` of `asset-index`

**Comment by mattsse** [comment]
In the runtime this is configured like this:

https://github.com/ChainSafe/PINT/blob/main/runtime/src/lib.rs#L551

https://github.com/ChainSafe/PINT/blob/main/runtime/src/lib.rs#L656

So basically `asset-index` > `price-feed` > `chainlink-feed`

**Comment by clearloop** [comment]
> In the runtime this is configured like this:
> 
> https://github.com/ChainSafe/PINT/blob/main/runtime/src/lib.rs#L551
> 
> https://github.com/ChainSafe/PINT/blob/main/runtime/src/lib.rs#L656
> 
> So basically `asset-index` > `price-feed` > `chainlink-feed`

Yep, but we can call `ChainlinkFeed<T>` in the benchmark of `AssetIndex<T>` only if `AssetIndex<T: pallet_chainlink_feed::Config>`
